# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '病历', 'verbose_name_plural': '病历'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': '医生', 'verbose_name_plural': '医生'},
        ),
        migrations.AlterModelTable(
            name='case',
            table='Case',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='Doctor',
        ),
    ]
