# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20190320_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='alt',
        ),
        migrations.AddField(
            model_name='case',
            name='dat',
            field=models.FileField(default=1, upload_to='file/dat', verbose_name='alt文件'),
            preserve_default=False,
        ),
    ]
