# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-20 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20190320_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='atr',
            field=models.FileField(upload_to='file', verbose_name='atr文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='dat',
            field=models.FileField(upload_to='file', verbose_name='dat文件'),
        ),
        migrations.AlterField(
            model_name='case',
            name='hea',
            field=models.FileField(upload_to='file', verbose_name='hea文件'),
        ),
    ]
